# Generated by Django 5.2.4 on 2025-08-01 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='operation',
            name='resulting_balance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Баланс после операции'),
        ),
    ]
