# Generated by Django 5.2.4 on 2025-08-02 23:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_operation_resulting_balance'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='operation',
            name='operation_type',
            field=models.IntegerField(choices=[(1, 'Пополнение'), (2, 'Перевод')], default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='account',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='user_account', to=settings.AUTH_USER_MODEL, verbose_name='Держатель счета'),
        ),
    ]
