# Generated by Django 5.2.4 on 2025-08-02 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_operation_operation_type_alter_account_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operation',
            name='type',
        ),
    ]
