# Generated by Django 5.2.4 on 2025-08-02 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_operation_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='operation',
            old_name='operation_type',
            new_name='type',
        ),
    ]
